# (continuing from line 200 of config.py)
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 8,
            "default_steps": 4,
            "uncensored": False,
            "quality": "fast_next_gen",
            "description": "FLUX 2.0 Schnell - Next-gen speed optimization"
        },
        
        # === KONTEXT SERIES - IN-CONTEXT EDITING ===
        "flux-kontext": {
            "endpoint": "fal-ai/flux-kontext",
            "cost_per_generation": 0.09,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": False,
            "quality": "context_aware",
            "special_features": ["in_context_editing", "enhanced_diversity"],
            "description": "FLUX Kontext - In-context generation for complex scenes"
        },
        "flux-kontext-pro": {
            "endpoint": "fal-ai/flux-kontext-pro", 
            "cost_per_generation": 0.13,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 30,
            "uncensored": False,
            "quality": "professional_context",
            "special_features": ["professional_in_context", "enhanced_diversity"],
            "description": "FLUX Kontext Pro - Professional in-context generation"
        },
        
        # === SPECIALIZED TOOLS ===
        "flux-fill": {
            "endpoint": "fal-ai/flux/fill",
            "cost_per_generation": 0.06,
            "max_resolution": "2048x2048",
            "supports_lora": False,
            "supports_controlnet": False,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": False,
            "quality": "specialized",
            "special_features": ["inpainting", "outpainting"],
            "description": "FLUX Fill - Advanced inpainting and outpainting"
        },
        "flux-depth": {
            "endpoint": "fal-ai/flux/depth",
            "cost_per_generation": 0.06,
            "max_resolution": "2048x2048",
            "supports_lora": False,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": False,
            "quality": "depth_aware",
            "special_features": ["depth_conditioning"],
            "description": "FLUX Depth - Depth-conditioned generation"
        },
        "flux-canny": {
            "endpoint": "fal-ai/flux/canny",
            "cost_per_generation": 0.06,
            "max_resolution": "2048x2048",
            "supports_lora": False,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": False,
            "quality": "edge_guided",
            "special_features": ["canny_edge_control"],
            "description": "FLUX Canny - Edge-guided generation"
        },
        "flux-redux": {
            "endpoint": "fal-ai/flux/redux",
            "cost_per_generation": 0.08,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": False,
            "quality": "enhanced_control",
            "special_features": ["style_transfer", "enhanced_prompting"],
            "description": "FLUX Redux - Enhanced style and composition control"
        },
        
        # === LORA ENHANCED MODELS ===
        "flux-dev-lora": {
            "endpoint": "fal-ai/flux-lora",
            "cost_per_generation": 0.07,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": False,
            "quality": "lora_optimized",
            "special_features": ["optimized_lora_support", "multiple_loras"],
            "description": "FLUX Dev LoRA - Optimized for LoRA fine-tuning"
        },
        "flux-dev-krea": {
            "endpoint": "fal-ai/flux-dev-krea",
            "cost_per_generation": 0.06,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 20,
            "uncensored": False,
            "quality": "enhanced_diversity",
            "special_features": ["enhanced_diversity", "creative_prompting"],
            "description": "FLUX Dev Krea - Enhanced diversity and creativity"
        },
        "flux-pro-finetuned": {
            "endpoint": "fal-ai/flux-pro-finetuned",
            "cost_per_generation": 0.11,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": True,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 30,
            "uncensored": False,
            "quality": "fine_tuned",
            "special_features": ["professional_fine_tuning"],
            "description": "FLUX Pro Fine-tuned - Professionally fine-tuned model"
        },
        
        # === NSFW/UNCENSORED MODELS (18+ ONLY) ===
        "flux-nsfw-ultimate": {
            "endpoint": "fal-ai/flux-nsfw-ultimate",
            "cost_per_generation": 0.10,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": False,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": True,
            "nsfw_enabled": True,
            "quality": "professional_nsfw",
            "special_features": ["uncensored_content", "adult_optimization"],
            "description": "FLUX NSFW Ultimate - Professional adult content generation",
            "age_restriction": "18+",
            "recommended_loras": ["flux-realistic-adult-v2", "flux-intimate-poses", "flux-body-enhancement"]
        },
        "flux-anime-nsfw-pro": {
            "endpoint": "fal-ai/flux-anime-nsfw-pro",
            "cost_per_generation": 0.09,
            "max_resolution": "2048x2048", 
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": False,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": True,
            "nsfw_enabled": True,
            "quality": "anime_nsfw",
            "special_features": ["anime_adult", "hentai_optimization"],
            "description": "FLUX Anime NSFW Pro - Professional anime adult content",
            "age_restriction": "18+",
            "recommended_loras": ["flux-anime-nsfw", "flux-waifu-explicit"]
        },
        "flux-fetish-specialist": {
            "endpoint": "fal-ai/flux-fetish-specialist",
            "cost_per_generation": 0.12,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": False,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 30,
            "uncensored": True,
            "nsfw_enabled": True,
            "quality": "fetish_specialized",
            "special_features": ["fetish_content", "extreme_adult"],
            "description": "FLUX Fetish Specialist - Specialized fetish content generation",
            "age_restriction": "18+",
            "recommended_loras": ["flux-bdsm-art", "flux-lingerie-specialist"]
        },
        "flux-artistic-erotic": {
            "endpoint": "fal-ai/flux-artistic-erotic",
            "cost_per_generation": 0.08,
            "max_resolution": "2048x2048",
            "supports_lora": True,
            "supports_controlnet": True,
            "supports_img2img": True,
            "supports_negative_prompt": True,
            "supports_scheduler": True,
            "supports_safety_tolerance": False,
            "supports_camera_controls": False,
            "max_steps": 50,
            "default_steps": 25,
            "uncensored": True,
            "nsfw_enabled": True,
            "quality": "artistic_adult",
            "special_features": ["artistic_nude", "erotic_art"],
            "description": "FLUX Artistic Erotic - High-art erotic content generation",
            "age_restriction": "18+",
            "recommended_loras": ["flux-erotic-art"]
        }
    }
    
    # Video Model Configuration with Comprehensive Support
    video_models: dict = {
        # === KLING AI SERIES ===
        "kling-ai-1.5-standard": {
            "endpoint": "fal-ai/kling-video/v1.5/standard",
            "provider": "kling",
            "cost_per_generation": 12,
            "max_duration": 5,
            "quality": "standard",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Kling AI 1.5 Standard - Cost-effective video generation"
        },
        "kling-ai-1.5-pro": {
            "endpoint": "fal-ai/kling-video/v1.5/pro",
            "provider": "kling",
            "cost_per_generation": 18,
            "max_duration": 10,
            "quality": "professional",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Kling AI 1.5 Pro - Enhanced quality and duration"
        },
        "kling-ai-1.6-standard": {
            "endpoint": "fal-ai/kling-video/v1.6/standard",
            "provider": "kling",
            "cost_per_generation": 15,
            "max_duration": 5,
            "quality": "enhanced",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Kling AI 1.6 Standard - Improved generation quality"
        },
        "kling-ai-1.6-pro": {
            "endpoint": "fal-ai/kling-video/v1.6/pro", 
            "provider": "kling",
            "cost_per_generation": 22,
            "max_duration": 10,
            "quality": "premium",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Kling AI 1.6 Pro - Premium quality video generation"
        },
        "kling-ai-2.0-master": {
            "endpoint": "fal-ai/kling-video/v2.0/master",
            "provider": "kling",
            "cost_per_generation": 28,
            "max_duration": 10,
            "quality": "master",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Kling AI 2.0 Master - Flagship model with superior quality"
        },
        "kling-ai-2.1": {
            "endpoint": "fal-ai/kling-video/v2.1",
            "provider": "kling",
            "cost_per_generation": 25,
            "max_duration": 10,
            "quality": "cutting_edge",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Kling AI 2.1 - Latest generation with advanced features"
        },
        "kling-ai-2.1-premium": {
            "endpoint": "fal-ai/kling-video/v2.1/premium",
            "provider": "kling",
            "cost_per_generation": 35,
            "max_duration": 10,
            "quality": "ultra_premium",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Kling AI 2.1 Premium - Highest quality commercial grade"
        },
        
        # === GOOGLE VEO SERIES ===
        "veo-2": {
            "endpoint": "fal-ai/google-veo/v2",
            "provider": "google",
            "cost_per_generation": 30,
            "max_duration": 8,
            "quality": "google_premium",
            "supports_image_input": True,
            "supports_text_input": True,
            "supports_dialog_mode": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Google Veo 2 - Professional video generation with dialog support"
        },
        "veo-3": {
            "endpoint": "fal-ai/google-veo/v3",
            "provider": "google", 
            "cost_per_generation": 40,
            "max_duration": 10,
            "quality": "google_flagship",
            "supports_image_input": True,
            "supports_text_input": True,
            "supports_dialog_mode": True,
            "supports_start_frame": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "coming_soon": True,
            "description": "Google Veo 3 - Coming Soon! Next-gen video with dialog scenes"
        },
        "veo-3-fast": {
            "endpoint": "fal-ai/google-veo/v3-fast",
            "provider": "google",
            "cost_per_generation": 25,
            "max_duration": 5,
            "quality": "google_fast",
            "supports_image_input": True, 
            "supports_text_input": True,
            "supports_dialog_mode": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Google Veo 3 Fast - Optimized for speed and efficiency"
        },
        "veo-lite": {
            "endpoint": "fal-ai/google-veo/lite",
            "provider": "google",
            "cost_per_generation": 15,
            "max_duration": 5,
            "quality": "google_lite",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Google Veo Lite - Cost-effective Veo experience"
        },
        
        # === RUNWAY GEN-3 SERIES ===
        # NOTE: These use the native Runway API, not fal.ai
        "runway-gen-3": {
            "endpoint": "runway/gen3a_turbo",
            "provider": "runway",
            "cost_per_generation": 25,
            "max_duration": 10,
            "quality": "runway_turbo",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Runway Gen-3 Alpha Turbo - Fast professional video generation"
        },
        "runway-gen-3-alpha": {
            "endpoint": "runway/gen3a",
            "provider": "runway",
            "cost_per_generation": 40,
            "max_duration": 10,
            "quality": "runway_premium",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Runway Gen-3 Alpha - Premium quality video generation"
        },
        
        # === MINIMAX HAILUO SERIES ===
        "hailuo-minimax-02": {
            "endpoint": "fal-ai/minimax-hailuo/v02",
            "provider": "minimax",
            "cost_per_generation": 20,
            "max_duration": 6,
            "quality": "minimax_standard",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Hailuo Minimax 02 - Professional Chinese video generation"
        },
        "hailuo-director": {
            "endpoint": "fal-ai/minimax-hailuo/director",
            "provider": "minimax",
            "cost_per_generation": 32,
            "max_duration": 8,
            "quality": "minimax_director",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Hailuo Director - Cinematic quality video generation"
        },
        
        # === SEEDDANCE SERIES ===
        "seeddance-1.0-pro": {
            "endpoint": "fal-ai/seeddance/v1.0/pro",
            "provider": "seeddance",
            "cost_per_generation": 18,
            "max_duration": 5,
            "quality": "seeddance_pro",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Seeddance 1.0 Pro - Professional dance and movement generation"
        },
        "seeddance-1.0-lite": {
            "endpoint": "fal-ai/seeddance/v1.0/lite",
            "provider": "seeddance",
            "cost_per_generation": 12,
            "max_duration": 3,
            "quality": "seeddance_lite",
            "supports_image_input": True,
            "supports_text_input": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Seeddance 1.0 Lite - Fast and affordable movement generation"
        },
        
        # === WAN 2.2 HYBRID MODEL ===
        "wan-2.2": {
            "endpoint": "fal-ai/wan/v2.2",
            "provider": "wan",
            "cost_per_generation": 22,
            "max_duration": 8,
            "quality": "wan_hybrid",
            "supports_image_input": True,
            "supports_text_input": True,
            "supports_image_generation": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "WAN 2.2 - Hybrid image/video generation model"
        },
        "qwen-wan": {
            "endpoint": "fal-ai/qwen-wan/v2.2",
            "provider": "qwen",
            "cost_per_generation": 26,
            "max_duration": 8, 
            "quality": "qwen_hybrid",
            "supports_image_input": True,
            "supports_text_input": True,
            "supports_image_generation": True,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "description": "Qwen WAN 2.2 - Advanced hybrid generation with language understanding"
        }
    }
    
    class Config:
        env_file = ".env"

# Create settings instance
settings = Settings()
